version: '3'
services:
  motus:
    image: mastainvinecole/motus-service:latest
    environment:
      - PORT=3000
      - LOKI=http://loki:3100
    networks:
      - motus_network
      - monitoring_network
    deploy:
      mode: replicated
      replicas: 2
  authorization-service:
    image: mastainvinecole/authorization-service:latest
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - motus_network
  score-service:
    image: mastainvinecole/score-service:latest
    environment:
      - PORT=3002
    networks:
      - motus_network
  redis:
    image: redis
    container_name: redis
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    networks:
      - motus_network
  haproxy:
    image: mastainvinecole/haproxy-service
    ports:
      - "3005:3001"
      - "80:3001"
    expose:
      - 80
    networks:
      - motus_network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring_network
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring_network
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - monitoring_network
networks:
  motus_network:
    driver: bridge
  monitoring_network:
    driver: bridge
