version: '3'
services:
  motus1:
    image: mastainvinecole/sumot:latest
    environment:
      - PORT=3000
    networks:
      - motus_network
  motus2:
    image: mastainvinecole/sumot:latest
    environment:
      - PORT=3000
    networks:
      - motus_network
  score-service:
    image: mastainvinecole/score-service:latest
    environment:
      - PORT=3002
    networks:
      - motus_network
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - motus_network
  haproxy:
    image: mastainvinecole/haproxy-service
    ports:
      - "3005:3001"
    networks:
      - motus_network

networks:
  motus_network:
    driver: bridge
