global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]
  - job_name: "motus_service"
    scrape_interval: 10s
    static_configs:
      - targets: [ "motus:3000" ]